# Generated by Django 5.0.6 on 2024-05-20 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upisi',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='upisi',
            old_name='subject_id',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='korisnik',
            name='role_id',
        ),
        migrations.AlterField(
            model_name='korisnik',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.uloga'),
        ),
    ]
