# Generated by Django 5.0.6 on 2024-05-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_student_id_upisi_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predmet',
            name='izborni',
            field=models.CharField(choices=[('DA', 'da'), ('NE', 'ne')], default='NE', max_length=50),
        ),
        migrations.AddField(
            model_name='predmet',
            name='sem_izv',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='predmet',
            name='sem_red',
            field=models.IntegerField(default=1),
        ),
    ]
