# Generated by Django 5.0.6 on 2024-05-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_uloga_name_uloga_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upisi',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
