# Generated by Django 5.0.6 on 2024-05-22 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_upisi_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='upisi',
            unique_together={('student', 'subject')},
        ),
    ]
