# Generated by Django 5.0.6 on 2024-05-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_upisi_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uloga',
            name='role',
            field=models.CharField(choices=[('Professor', 'profesor'), ('Student', 'student'), ('Admin', 'admin')], default='adm', max_length=50),
        ),
    ]
