# Generated by Django 5.0.6 on 2024-05-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_uloga_role_alter_upisi_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
